services:
  - type: web
    name: ai-image-generation-flux
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /aigenpicfluxaiwithcolab
        destination: /aigenpicfluxaiwithcolab/index.html
      - type: rewrite  
        source: /aigenpicfluxaiwithcolab/*
        destination: /aigenpicfluxaiwithcolab/index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin